django_web_exceptions-0.1.1.dist-info/DESCRIPTION.rst,sha256=JwlTJar9nOdHRFPKM6Epo4KfOCCZ3sP8z2zqdVAiYxU,2832
django_web_exceptions-0.1.1.dist-info/METADATA,sha256=S7t9-mEAB1ttpb9ZmJjJX7TNJ5AXiF5zErev-CEdAPg,3612
django_web_exceptions-0.1.1.dist-info/RECORD,,
django_web_exceptions-0.1.1.dist-info/WHEEL,sha256=o2k-Qa-RMNIJmUdIc7KU6VWR_ErNRbWNlxDIpl7lm34,110
django_web_exceptions-0.1.1.dist-info/metadata.json,sha256=68SgIuAL13RNdlCPwD_B3oiz8G40uRDiJu7Rkm3A-UY,891
django_web_exceptions-0.1.1.dist-info/top_level.txt,sha256=wLetahU8QNvabnmEkZSF_ILDGUwLc6SIQW0FweaCJdA,15
web_exceptions/__init__.py,sha256=ls1camlIoMxEZz9gSkZ1OJo-MXqHWwKPtdPbZJmwp7E,22
web_exceptions/apps.py,sha256=qrii5Ds4Mb8TVpiWbICof_Ocrd5gsw7eaWpYTxpzgsc,102
web_exceptions/exceptions.py,sha256=7uwzlZxbVDvY4G5XshKFPi2mLPna4qeTi436cAoQtug,6786
web_exceptions/middleware.py,sha256=RRC1OVi2iLlSzLaICtxe22gRUjxN6BqBG2-I7uWl0Ao,709
